### ISSUE TITLE
Browser sizing issue

### ISSUE THREAD

**Issue by ktsenvolt** [AnsonLai/TeslaServiceManualScraper#10]
![fullscreen](https://user-images.githubusercontent.com/80360674/177439999-89e6d4d6-f74b-4cfc-ac20-a8159b2e8a1d.jpg)
![partial screen](https://user-images.githubusercontent.com/80360674/177440079-0eca4d40-aeb0-4559-bcf7-97d8a6a82e38.jpg)
There are some issues with any browser sizing. As you can see it would work with full screen and some files are missing.
I can see the whole picture with only a partial browser.

**Comment by hlarsen** [comment]
not sure if it's the same thing i'm seeing; try removing `height: 100%` from the steps:

`article > div[.body,.taskbody] > ol > li`

cleans it up for me. might have to do with `design-system` css being 5.x instead of 5.4.1 the code is looking for

**Comment by ktsenvolt** [comment]
.steps > .step {
    margin-top: 1rem;
    # height: 100%;
  }
After I put # before the height. It works. Thank you.
