### ISSUE TITLE
New Tip: Search Functionality

### ISSUE THREAD

**Issue by TheNexusAvenger** [AnsonLai/TeslaServiceManualScraper#3]
Under the Tips section, there is a mention of getting other files for the styling of the website. [While trying out a local download of the Model Y service manual](https://twitter.com/TheNexusAvenger/status/1527874386283442181), I noticed there is another `index.json` file that can be downloaded to get searching. The main caveat is that the search functionality requires fetching that file over an HTTP request, which necessitates running the manual with an HTTP server. `python -m http.server` works just fine from what I can tell. Adding these 2 notes may be beneficial.

**Comment by AnsonLai** [comment]
Do you know where this index.json file is?  I'm not seeing it in sources, and frankly the lack of a search feature does bother me big time hahah.

Thanks!

**Comment by TheNexusAvenger** [comment]
`index.json` is fetched the first time a search is performed and is appended to the base URL of the service manual. For the Model 3, which is at `https://service.tesla.com/docs/Model3/ServiceManual/en-us/`, the `index.json` file is at `https://service.tesla.com/docs/Model3/ServiceManual/en-us/index.json`.

**Comment by AnsonLai** [comment]
Awesome, just updated the scrape.py to fetch the index.json file as well.  I'm having a bit of trouble with the http.server, so search is still broken for me.  I'll test this out in a bit.  Thanks for the tips!

**Comment by AnsonLai** [comment]
Everything working!  Awesome stuff dude!
