### ISSUE TITLE
unable to scrap help

### ISSUE THREAD

**Issue by decodering22** [AnsonLai/TeslaServiceManualScraper#7]
Can i get some help.
Had to make some tweaks to get it to even download. But now it is downloading and after a while the browser closes exactly at the same spot every time it is downloading the Model S manual it gets to section 12 and just closes the Brower, opens back up and I authenticate again but it starts at the very beginning of the manual. It does not pickup from section 12. 

Any help is appreciated? 

***Changes to the requirements document
beautifulsoup4==4.10.0
certifi==2020.11.8
chardet==3.0.4
future==0.18.2
idna==2.10
lxml==4.8.0
Pillow==9.1.1
pywin32-ctypes==0.2.0
requests==2.25.1
soupsieve==2.2.1
urllib3==1.26.2
zipp==3.4.0

**Comment by decodering22** [comment]
Starting from scratch again this time I didn't want to make any changes to your instructions. 

Getting to step 6 this is the error I get, the way I got around this was changing the pillow version in the file previously but i'll instead wait to see what you recommend.



 C:\Users\testUser\AppData\Local\Temp\pip-install-cbvxvd_h\pillow_2f4e64ae17c34c2e9b0782862e6affb1\setup.py:46: RuntimeWarning: Pillow 8.3.1 does not support Python 3.10 and does not provide prebuilt Windows binaries. We do not recommend building from source on Windows.
        lambda: warnings.warn(
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> Pillow

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
WARNING: You are using pip version 22.0.4; however, version 22.1.1 is available.
You should consider upgrading via the 'C:\Users\testUser\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

**Comment by decodering22** [comment]
I changed the requirements to pillow=9.1.1 than i get this following error which was another issue i had to resolve. Can't for the life of me remember what i did but I'm about to research it again and see how to get around it.

      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      *********************************************************************************
      Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
      *********************************************************************************
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> lxml

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by Serial-Killa** [comment]
Even after updating pip / modules  it seems that the script runs for a bit then encounters the following:
Seems to never finish getting the HTML files. never makes it to the Images. 

`Traceback (most recent call last):
  File "C:\Users\zero\Desktop\TeslaServiceManualScraper-master\scrape.py", line 262, in <module>
    run()
  File "C:\Users\zero\Desktop\TeslaServiceManualScraper-master\scrape.py", line 255, in run
    driver.get_html()
  File "C:\Users\zero\Desktop\TeslaServiceManualScraper-master\scrape.py", line 146, in get_html
    self.restart_scrape()
  File "C:\Users\zero\Desktop\TeslaServiceManualScraper-master\scrape.py", line 43, in restart_scrape
    run()
  File "C:\Users\zero\Desktop\TeslaServiceManualScraper-master\scrape.py", line 255, in run
    driver.get_html()
  File "C:\Users\zero\Desktop\TeslaServiceManualScraper-master\scrape.py", line 146, in get_html
    self.restart_scrape()
  File "C:\Users\zero\Desktop\TeslaServiceManualScraper-master\scrape.py", line 43, in restart_scrape
    run()
  File "C:\Users\zero\Desktop\TeslaServiceManualScraper-master\scrape.py", line 255, in run
    driver.get_html()
  File "C:\Users\zero\Desktop\TeslaServiceManualScraper-master\scrape.py", line 146, in get_html
    self.restart_scrape()
  File "C:\Users\zero\Desktop\TeslaServiceManualScraper-master\scrape.py", line 43, in restart_scrape
    run()
  File "C:\Users\zero\Desktop\TeslaServiceManualScraper-master\scrape.py", line 255, in run
    driver.get_html()
  File "C:\Users\zero\Desktop\TeslaServiceManualScraper-master\scrape.py", line 146, in get_html
    self.restart_scrape()
  File "C:\Users\zero\Desktop\TeslaServiceManualScraper-master\scrape.py", line 43, in restart_scrape
    run()
  File "C:\Users\zero\Desktop\TeslaServiceManualScraper-master\scrape.py", line 255, in run
    driver.get_html()
  File "C:\Users\zero\Desktop\TeslaServiceManualScraper-master\scrape.py", line 146, in get_html
    self.restart_scrape()
  File "C:\Users\zero\Desktop\TeslaServiceManualScraper-master\scrape.py", line 43, in restart_scrape
    run()
  File "C:\Users\zero\Desktop\TeslaServiceManualScraper-master\scrape.py", line 255, in run
    driver.get_html()
  File "C:\Users\zero\Desktop\TeslaServiceManualScraper-master\scrape.py", line 146, in get_html
    self.restart_scrape()
  File "C:\Users\zero\Desktop\TeslaServiceManualScraper-master\scrape.py", line 43, in restart_scrape
    run()
  File "C:\Users\zero\Desktop\TeslaServiceManualScraper-master\scrape.py", line 255, in run
    driver.get_html()
  File "C:\Users\zero\Desktop\TeslaServiceManualScraper-master\scrape.py", line 146, in get_html
    self.restart_scrape()
  File "C:\Users\zero\Desktop\TeslaServiceManualScraper-master\scrape.py", line 43, in restart_scrape
    run()
  File "C:\Users\zero\Desktop\TeslaServiceManualScraper-master\scrape.py", line 251, in run
    driver.get_index()
  File "C:\Users\zero\Desktop\TeslaServiceManualScraper-master\scrape.py", line 52, in get_index
    window1 = driver.window_handles[1]
IndexError: list index out of range`

**Comment by decodering22** [comment]
How did you get to that point, I'm having a hell of a time

**Comment by decodering22** [comment]
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#form-submit-continue"}
  (Session info: chrome=102.0.5005.63)

Not sure how to get around this to begin downloading. Any suggestions?

**Comment by Serial-Killa** [comment]
> selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#form-submit-continue"} (Session info: chrome=102.0.5005.63)
> 
> Not sure how to get around this to begin downloading. Any suggestions?

Assuming you are using windows,   how did you install the PIP modules?   using the install -r requirements.txt didnt work so I installed them all manually.   in windows the python commands are  py -m pip install  nameofmodule

you can check what you have installed by using py -m pip list

I didnt do anything crazy.  I have the current ver of python installed on windows 11.  I just downloaded the zip, extracted , installed modules   cd' to the directory and ran the scrape.py.

**Comment by decodering22** [comment]
I was able to actually get it to download but i had to not only modify the requirements but make changes to the secrets.py file. it is downloading now but the problem is the browser closes and restarts and once i put in the credentials it starts at the very top and does not continue from where it left off. quite irritating.

**Comment by decodering22** [comment]
I don't know why the browser closes at all in the first place after it gets to like section 12 of the manual than it just restarts from the top. 

hopefully the developer can chime in on both our problems, and I'm on windows 10

**Comment by decodering22** [comment]
Can i get some help.
Had to make some tweaks to get it to even download. But now it is downloading and after a while the browser closes. Opens back up and I authenticate again but it starts at the very beginning of the manual.

***Changes to the requirements document
beautifulsoup4==4.10.0
certifi==2020.11.8
chardet==3.0.4
future==0.18.2
idna==2.10
lxml==4.8.0
Pillow==9.1.1
pywin32-ctypes==0.2.0
requests==2.25.1
soupsieve==2.2.1
urllib3==1.26.2
zipp==3.4.0

***Change to scrips for Windows users
This was the only way I could get the scraper to start otherwise it was throwing other errors related to the commands commented. 
import time

# TODO: Input your tesla account details
tesla_account_email = "email"
tesla_account_password = "pass"
login_delay = 15

def tesla_login(driver):
  driver.get("https://tesla.com/teslaaccount")
  driver.find_element_by_css_selector("#form-input-identity").send_keys(tesla_account_email)
  time.sleep(10 + login_delay)
 # driver.find_element_by_css_selector("#form-submit-continue").click()
 # time.sleep(10 + login_delay)
 # driver.find_element_by_css_selector("#form-input-credential").send_keys(tesla_account_password)
 # time.sleep(10 + login_delay)
 # driver.find_element_by_css_selector("#form-submit-continue").click()

  return driver

**Comment by decodering22** [comment]
Also it does not download any of the images only the pages so far. I recall it downloads the pages first than images but the CMD prompt is a little misleading

example below it shows:
visited: 79
upcoming: 892
images: 252
visited: 80
upcoming: 891
images: 255
visited: 81
upcoming: 890
images: 256

**Comment by AnsonLai** [comment]
There seems to be a few issues here, but there was definitely a bug.  The browser should restart, it is preemptively stopping Tesla from booting users out, but the bug is that it wasn't saving before the restart kicks in, so it restarts from the top.  Sorry about that, that's a breaking bug right there!

Unfortunately for the modules, I'm not sure I can help.  Selenium and chromedriver are notorious for having all sorts of gotchas.  I really didn't want to use Selenium but it was the quickest way to get this running for me.  I didn't think a ton of people would be using it, I just thought it was fun to share.  In retrospect, Selenium is no fun.

**Comment by Serial-Killa** [comment]
I think decoderring22 isnt using the latest version of your app.  I went to yesterdays version and received the same bug he did with the selenium.common.exception. 

so @decodering22  pull the latest zip after @AnsonLai  fixes the resume bug on restart.  that should resolve your issue.

**Comment by decodering22** [comment]
I  downloaded the latest as i only started to play with this today. I'm pretty sure it is the latest that has this bug. Unless you are saying to pull the latest after @AnsonLai fixes the bug than yes that is my plan. 

@AnsonLai thanks for the confirmation it is supposed to close and restart. That is reassuring. As far as saving i can definitely see in the folder it has harvested all the HTML files up to the point before it restarts, none of the images are saved however. Do you have any ideas why it would not restart from the previous place? I'm not a developer but dangerous enough to break things and test things out. I spent so much on this i'm determined to get it to work and will share the file with you guys once I can confirm it works and downloads everything. 

Thanks again for your effort. Figure get it now before Tesla stops people from downloading it.

**Comment by decodering22** [comment]
Here is the output of the endless loop it is stuck in in the console:

DevTools listening on ws://127.0.0.1:56970/devtools/browser/651aa28e-7192-4873-83e7-b1956a5e1aa2
****** SESSION LOADED ******
****** SESSION SAVED ******
****** SESSION SAVED ******
****** SESSION SAVED ******
visited: 901
upcoming: 70
images to be downloaded: 7561
visited: 902
upcoming: 69
images to be downloaded: 7571
visited: 903
upcoming: 68
images to be downloaded: 7571
visited: 904
upcoming: 67
images to be downloaded: 7575
visited: 905
upcoming: 66
images to be downloaded: 7576
visited: 906
upcoming: 65
images to be downloaded: 7576
visited: 907
upcoming: 64
images to be downloaded: 7579
visited: 908
upcoming: 63
images to be downloaded: 7581
visited: 909
upcoming: 62
images to be downloaded: 7583
visited: 910
upcoming: 61
images to be downloaded: 7631
visited: 911
upcoming: 60
images to be downloaded: 7635
[9900:4468:0526/232019.497:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is disabled, ANGLE is
visited: 912
upcoming: 59
images to be downloaded: 7674
visited: 913
upcoming: 58
images to be downloaded: 7676
visited: 914
upcoming: 57
images to be downloaded: 7676
visited: 915
upcoming: 56
images to be downloaded: 7676
visited: 916
upcoming: 55
images to be downloaded: 7677
visited: 917
upcoming: 54
images to be downloaded: 7677
visited: 918
upcoming: 53
images to be downloaded: 7679
visited: 919
upcoming: 52
images to be downloaded: 7684
visited: 920
upcoming: 51
images to be downloaded: 7686
visited: 921
upcoming: 50
images to be downloaded: 7686
visited: 922
upcoming: 49
images to be downloaded: 7690
visited: 923
upcoming: 48
images to be downloaded: 7703
visited: 924
upcoming: 47
images to be downloaded: 7720
visited: 925
upcoming: 46
images to be downloaded: 7736
visited: 926
upcoming: 45
images to be downloaded: 7738
visited: 927
upcoming: 44
images to be downloaded: 7738
visited: 928
upcoming: 43
images to be downloaded: 7746
visited: 929
upcoming: 42
images to be downloaded: 7749
visited: 930
upcoming: 41
images to be downloaded: 7750
visited: 931
upcoming: 40
images to be downloaded: 7755
visited: 932
upcoming: 39
images to be downloaded: 7764
visited: 933
upcoming: 38
images to be downloaded: 7764
visited: 934
upcoming: 37
images to be downloaded: 7775
visited: 935
upcoming: 36
images to be downloaded: 7780

DevTools listening on ws://127.0.0.1:57031/devtools/browser/6d6fe0de-86f6-4fdc-8101-0bf8325b53ae
****** SESSION LOADED ******
****** SESSION SAVED ******
****** SESSION SAVED ******
****** SESSION SAVED ******

**Comment by AnsonLai** [comment]
I know exactly what is wrong here for once.  The model 3 manual seems to link to a few pages that the user doesn't have access to.

I created a tolerance threshold just now and pushed that out.  But you can skip it entirely, comment out lines 130 and 131 in scrape.py and I think you're in the home stretch!

**Comment by decodering22** [comment]
Awesome let me try that right now. thanks

**Comment by decodering22** [comment]
Well now this is interesting commenting out 130 and 131  results in this error, after it authenticates it goes to the you do not  have access page like it always does but instead of opening the service manual it closes the browser and give this error below:

  File "C:\Users\testuser\Desktop\TeslaServiceManualScraper-master\scrape.py", line 137, in get_html
    source = re.sub(mpulse_tracker, '', source)
UnboundLocalError: local variable 'source' referenced before assignment

**Comment by AnsonLai** [comment]
Are you sure you're commenting out the right lines?  You need to leave this intact:
source = self.driver.find_element_by_css_selector("html").get_attribute('outerHTML')

Comment out these two lines:
        if not check_source_validity(source):
            self.restart_scrape()

**Comment by decodering22** [comment]
I put 130 and 131 back in but changed 133 to 100 from 10 and it went into a loop on can't access this page so i killed the browser. 

I'm going to call it a night and check your comment tomorrow to give it another go. It is at the end of the manual before it start to download pictures so almost there.

**Comment by decodering22** [comment]
Let me try it again now with just 130 and 134 commented out instead.

**Comment by decodering22** [comment]
Doesn't like that, i believe your intent is to also comment out 132 & 133 as well correct just leaving 130 alone, which is now running waiting to see if it loops again

C:\Users\AF-NUC\Desktop\TeslaServiceManualScraper-master>python scrape.py
  File "C:\Users\testuser\Desktop\TeslaServiceManualScraper-master\scrape.py", line 132
    error_count += 1
IndentationError: unexpected indent

**Comment by decodering22** [comment]
It is now going into the Unable to access File loop going to kill the browser so i don't get the VPN IP or account banned. Something is definitely not right as it gets near the end of the model S manual.

I can share the "docs" folder it is only 180MB, not sure if you run the script you will see exactly what I'm experiencing. 

Let me know your thoughts, ill try again tomorrow. Cheers

**Comment by decodering22** [comment]
you can see it keeps trying to repeat the same site which it does not have access to


upcoming: 953
images to be downloaded: 7822
visited: 963
upcoming: 952
images to be downloaded: 7829
visited: 964
upcoming: 951
images to be downloaded: 7861
visited: 965
upcoming: 950
images to be downloaded: 7867
visited: 966
upcoming: 949
images to be downloaded: 7890
visited: 967
upcoming: 948
images to be downloaded: 7890
visited: 968
upcoming: 947
images to be downloaded: 7896
visited: 969
upcoming: 946
images to be downloaded: 7896
visited: 970
upcoming: 945
images to be downloaded: 7896
visited: 971
upcoming: 944
images to be downloaded: 7896
visited: 972
upcoming: 943
images to be downloaded: 7896
visited: 973
upcoming: 942
images to be downloaded: 7896
visited: 974
upcoming: 941
images to be downloaded: 7896
visited: 975
upcoming: 940
images to be downloaded: 7896
visited: 976
upcoming: 939
images to be downloaded: 7896
visited: 977
upcoming: 938
images to be downloaded: 7896
visited: 978
upcoming: 937
images to be downloaded: 7896
visited: 979
upcoming: 936
images to be downloaded: 7896
visited: 980
upcoming: 935
images to be downloaded: 7896
visited: 981

**Comment by AnsonLai** [comment]
It seems that something must have gone wrong in an earlier version and you're running into an error.  None of the service manuals have 1800+ pages, and you're seeing that you visited 900 and still have another 900 to go.  I suspect in an earlier version of scrape.py, the URLs weren't being added to the visited list somehow.  You should start again by deleting dict.pickle and the data folder.  You should probably use the latest version of scrape.py as well.
